import jsPDF from 'jspdf';

export const generatePDFReport = (messages) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFillColor(22, 163, 74); // Green
    doc.rect(0, 0, pageWidth, 20, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.text('TravelDoctor.ai - Medical Report (SBAR)', 10, 13);

    // Metadata
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text(`Date: ${new Date().toLocaleString()}`, 10, 30);
    doc.text('This report is generated by an AI assistant.', 10, 35);

    let yPos = 45;

    // Content
    messages.forEach((msg, index) => {
        if (yPos > 280) {
            doc.addPage();
            yPos = 20;
        }

        doc.setFontSize(10);
        doc.setFont(undefined, 'bold');
        const role = msg.role === 'user' ? 'Patient' : 'AI Doctor';
        doc.setTextColor(msg.role === 'user' ? '#16a34a' : '#000000');
        doc.text(`${role}:`, 10, yPos);

        doc.setFont(undefined, 'normal');
        doc.setTextColor(0, 0, 0);

        // Wrap text
        const splitText = doc.splitTextToSize(msg.text, 180);
        doc.text(splitText, 10, yPos + 5);

        yPos += (splitText.length * 5) + 10;
    });

    // Footer / Disclaimer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Disclaimer: This is not an official medical document. Consult a professional.', 10, 290);

    doc.save('TravelDoctor_Report.pdf');
};
